CREATE TABLE [dbo].[Users] (
    [Id]                   INT                IDENTITY (1, 1) NOT NULL,
    [DateOfBirth]          DATE               NOT NULL,
    [KnownAs]              NVARCHAR (MAX)     NOT NULL,
    [Created]              DATETIME2 (7)      NOT NULL,
    [LastActive]           DATETIME2 (7)      NOT NULL,
    [Gender]               NVARCHAR (MAX)     NOT NULL,
    [Introduction]         NVARCHAR (MAX)     NULL,
    [LookingFor]           NVARCHAR (MAX)     NULL,
    [Interests]            NVARCHAR (MAX)     NULL,
    [City]                 NVARCHAR (MAX)     NOT NULL,
    [Country]              NVARCHAR (MAX)     NOT NULL,
    [UserName]             NVARCHAR (MAX)     NULL,
    [NormalizedUserName]   NVARCHAR (MAX)     NULL,
    [Email]                NVARCHAR (MAX)     NULL,
    [NormalizedEmail]      NVARCHAR (MAX)     NULL,
    [EmailConfirmed]       BIT                NOT NULL,
    [PasswordHash]         NVARCHAR (MAX)     NULL,
    [SecurityStamp]        NVARCHAR (MAX)     NULL,
    [ConcurrencyStamp]     NVARCHAR (MAX)     NULL,
    [PhoneNumber]          NVARCHAR (MAX)     NULL,
    [PhoneNumberConfirmed] BIT                NOT NULL,
    [TwoFactorEnabled]     BIT                NOT NULL,
    [LockoutEnd]           DATETIMEOFFSET (7) NULL,
    [LockoutEnabled]       BIT                NOT NULL,
    [AccessFailedCount]    INT                NOT NULL,
    CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([Id] ASC)
);

